"use client";
import { useRef, useState } from "react";
export type Photo = { src: string; alt: string };
export type PhotoStackProps = { photos: Photo[] };
type PointerState = { id: number; startX: number; startY: number; deltaX: number; deltaY: number; moved: boolean };
const RELEASE_MS = 300;
const clamp = (value: number, min: number, max: number) => Math.min(Math.max(value, min), max);
export function PhotoStack({ photos }: PhotoStackProps) { const [order, setOrder] = useState(() => photos.map((_, index) => index)); const [drag, setDrag] = useState({ x: 0, y: 0, rotate: 0 }); const [exit, setExit] = useState({ x: 40, y: 0, rotate: 4 }); const [isExiting, setIsExiting] = useState(false); const [isDragging, setIsDragging] = useState(false); const pointer = useRef<PointerState | null>(null); const advance = (deltaX: number, deltaY: number) => { if (isExiting || order.length < 2) return; const direction = Math.abs(deltaX) > 5 ? Math.sign(deltaX) : 1; setExit({ x: Math.abs(deltaX) > 5 ? deltaX * 2 + direction * 120 : direction * 40, y: Math.abs(deltaY) > 5 ? deltaY * 0.5 : 0, rotate: clamp((deltaX || direction * 10) * 0.025, -7, 7) }); setDrag({ x: 0, y: 0, rotate: 0 }); setIsExiting(true); window.setTimeout(() => { setOrder(current => [...current.slice(1), current[0]]); setIsExiting(false); }, RELEASE_MS); };
const onPointerDown = (event: React.PointerEvent<HTMLDivElement>) => { if (isExiting || order.length < 2) return; event.currentTarget.setPointerCapture(event.pointerId); setIsDragging(true); pointer.current = { id: event.pointerId, startX: event.clientX, startY: event.clientY, deltaX: 0, deltaY: 0, moved: false }; };
const onPointerMove = (event: React.PointerEvent<HTMLDivElement>) => { const current = pointer.current; if (!current || current.id !== event.pointerId || isExiting) return; current.deltaX = event.clientX - current.startX; current.deltaY = event.clientY - current.startY; current.moved = Math.hypot(current.deltaX, current.deltaY) >= 5; setDrag({ x: current.deltaX, y: current.deltaY, rotate: clamp(current.deltaX * 0.025, -7, 7) }); };
const onPointerUp = (event: React.PointerEvent<HTMLDivElement>) => { const current = pointer.current; if (!current || current.id !== event.pointerId) return; pointer.current = null; setIsDragging(false); if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); advance(current.deltaX, current.deltaY); };
const onPointerCancel = (event: React.PointerEvent<HTMLDivElement>) => { const current = pointer.current; if (!current || current.id !== event.pointerId) return; pointer.current = null; setIsDragging(false); if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); if (current.moved) advance(current.deltaX, current.deltaY); else setDrag({ x: 0, y: 0, rotate: 0 }); };
const onKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); advance(0, 0); } };
return <div className={"photo-stack" + (isExiting ? " is-exiting" : "") + (isDragging ? " is-dragging" : "")} role="button" tabIndex={0} aria-label="Mostrar próxima foto" onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerCancel} onKeyDown={onKeyDown}>{order.map((photoIndex, stackIndex) => { const photo = photos[photoIndex]; const isFront = stackIndex === 0; const style = isFront ? { "--drag-x": drag.x + "px", "--drag-y": drag.y + "px", "--exit-x": exit.x + "px", "--exit-y": exit.y + "px", "--exit-rotate": exit.rotate + "deg", "--drag-rotate": drag.rotate + "deg" } : undefined; return <img key={photo.src} className={"photo-stack-card" + (isFront ? " is-front" : "")} src={photo.src} alt={photo.alt} draggable={false} style={style as React.CSSProperties}/>; })}</div> }
